### ISSUE TITLE
something missing

### ISSUE THREAD

**Issue by SNEF-CBI** [Seeed-Studio/Seeed_Python_ReTerminalQt5Examples#2]
Hi again,

for this last parts : 
```
git clone git://code.qt.io/qt/qtquicktimeline
cd qtquicktimeline
qmake 
make
sudo make install 
```

qmake did'nt do anything, like a missing configuration file for this git repository

**Comment by lakshanthad** [comment]
Hello,

Could you please tell me your environment?

- Hardware used
- OS installed
- And more info

Thank you

**Comment by jsb5151** [comment]
Same issue here.  Fresh Raspberry Pi OS 64-bit (Debian 11 Bullseye)

**Comment by lakshanthad** [comment]
Hello @SNEF-CBI @SNEF-CBI,

I have tried it and it seems you need to install the compilation tools by separating into two as follows:

```
sudo apt install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
sudo apt install qtdeclarative5-private-dev qtbase5-private-gles-dev
```

After that please try again.

I have updated the README as well.

Thank you.

**Comment by SNEF-CBI** [comment]
Hi,

I use Fresh reTerminal without any update (receive today)

**Comment by lakshanthad** [comment]
> Hi,
> 
> I use Fresh reTerminal without any update (receive today)

Hello,
If you have fresh reTerminal, you do not need to install anything for Qt. Everything is pre-installed. Also the Qt demo app you find in this repo is pre-installed. You can see an icon of the demo app on the RPi OS Desktop and can open it by double clicking it.

**Comment by jsb5151** [comment]
I don't see any .pro file in the qtquicktimeline dir/repo so that's probably why it's not working.

**Comment by lakshanthad** [comment]
Hello @jsb5151,

Please follow this:

**Step 1:**
Execute the following:

```
sudo apt install at-spi2-core onboard qml-module-qtquick-shapes python3-pyside2.qtqml python3-pyside2.qtcore python3-pyside2.qtnetwork python3-pyside2.qtgui python3-pyside2.qtwidgets python3-pyside2.qtquick qtquickcontrols2-5-dev qml-module-qtcharts qml-module-qtquick-controls qml-module-qtquick-controls2 python3-evdev python3-psutil
```

**Step 2:**
Replace "Seeed_Python_ReTerminalQt5Examples/imports/aarch64/QtQuick" with the file below:
https://files.seeedstudio.com/wiki/ReTerminal/Qt/QtQuick.tar.gz

And let me know the result

Thank you.

**Comment by lakshanthad** [comment]
Hello,

Please check my updated instructions:
https://github.com/Seeed-Studio/Seeed_Python_ReTerminalQt5Examples/blob/main/README.md

**Comment by bigbearishappy** [comment]
Closing this issue. If you have any further problem. Please reopen it or create a new one.
Thank you guys~
